version: '3'
services:
  practice-product:
    #container_name: practice-product
    image:  practice-product
    ports:
      - 9001-9030:8080
    environment:
      MYSQL_HOST: ska-mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
    depends_on:
      -  ska-mysqldb

  ska-mysqldb:
    container_name: ska-mysqldb
    image: mysql:5.7
    ports:
        - 3307:3306
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_ROOT_PASSWORD: root


