version: '3'
services:
  practice-product:
    #container_name: practice-product
    image:  sandeep022/practice-product:9
    ports:
      - 9001-9030:8081
    environment:
      MYSQL_HOST: ska-mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
    depends_on:
      -  ska-mysqldb

  ska-mysqldb:
    container_name: ska-mysqldb
    image: mysql
    ports:
        - 3307:3306
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_ROOT_PASSWORD: root


