#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/testdb
#spring.datasource.username=${MYSQL_USER:laravel}
#spring.datasource.password=${MYSQL_PASSWORD:laravel}
server:
  port: 8081

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:192.168.0.102}:${MYSQL_PORT:3307}/testdb
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    serviceUrl:
      # Location of your eureka server
      defaultZone: http://${service-registory16:192.168.0.102}:8761/eureka



