#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/testdb
#spring.datasource.username=${MYSQL_USER:laravel}
#spring.datasource.password=${MYSQL_PASSWORD:laravel}
server:
  port: 8081

spring:
  application:
    name: product-practice
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/testdb
    username: ${MYSQL_USER:laravel}
    password: ${MYSQL_PASSWORD:laravel}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true


